name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Node.js and dependencies
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Check for changes in the functions folder
        id: functions-changes
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          if echo "$CHANGED_FILES" | grep -q "functions/"; then
            echo "Firebase functions changed"
            echo "::set-output name=firebase_functions::true"
          else
            echo "No Firebase functions changes"
            echo "::set-output name=firebase_functions::false"
          fi

      - name: Deploy Firebase functions
        if: steps.changes.outputs.firebase_functions == 'true'
        run: |
          cd functions
          npm install
          firebase deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy Quasar app
        if: steps.changes.outputs.firebase_functions != 'true'
        run: |
          npm install
          quasar build
          firebase deploy --only hosting
        env:
          VUE_APP_FIREBASE_API_KEY: ${{ secrets.VUE_APP_FIREBASE_API_KEY }}
          VUE_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.VUE_APP_FIREBASE_AUTH_DOMAIN }}
          VUE_APP_FIREBASE_PROJECT_ID: ${{ secrets.VUE_APP_FIREBASE_PROJECT_ID }}
          VUE_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.VUE_APP_FIREBASE_STORAGE_BUCKET }}
          VUE_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VUE_APP_FIREBASE_MESSAGING_SENDER_ID }}
          VUE_APP_FIREBASE_APP_ID: ${{ secrets.VUE_APP_FIREBASE_APP_ID }}
          VUE_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.VUE_APP_FIREBASE_MEASUREMENT_ID }}
          POLYGON_KEY: ${{ secrets.POLYGON_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}

